import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  CalendarPlus,
  MapPin,
  Clock,
  Video,
  ExternalLink,
  MessageSquare,
  Download,
  Share2,
} from "lucide-react";
import { useState } from "react";
import type { UpcomingMeeting } from "@shared/schema";

/** Generate a Google Calendar event URL */
function googleCalUrl(m: UpcomingMeeting): string {
  // Convert date + time to ISO format for Google Calendar
  const { h24, min } = parseTime(m.time);
  const dt = `${m.date.replace(/-/g, "")}T${String(h24).padStart(2, "0")}${String(min).padStart(2, "0")}00`;
  const endH = h24 + 2;
  const endDt = `${m.date.replace(/-/g, "")}T${String(endH).padStart(2, "0")}${String(min).padStart(2, "0")}00`;

  const title = encodeURIComponent(`${m.governing_body} — ${m.meeting_type}`);
  const details = encodeURIComponent(
    `${m.governing_body} ${m.meeting_type}\n\n` +
    `📍 ${m.location_name}\n${m.location}\n\n` +
    (m.public_comment ? "🎙️ Public comment period available\n\n" : "") +
    (m.live_stream_url ? `📺 Live Stream: ${m.live_stream_url}\n` : "") +
    (m.agenda_url ? `📋 Agenda: ${m.agenda_url}\n` : "") +
    `\nSource: ${m.source_url}\n\nGenerated by PGH Civic Pulse`
  );
  const location = encodeURIComponent(`${m.location_name}, ${m.location}`);

  return `https://www.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dt}/${endDt}&ctz=${m.timezone}&details=${details}&location=${location}`;
}

/** Generate .ics file content */
function generateIcs(m: UpcomingMeeting): string {
  const { h24, min } = parseTime(m.time);
  const dt = `${m.date.replace(/-/g, "")}T${String(h24).padStart(2, "0")}${String(min).padStart(2, "0")}00`;
  const endH = h24 + 2;
  const endDt = `${m.date.replace(/-/g, "")}T${String(endH).padStart(2, "0")}${String(min).padStart(2, "0")}00`;

  const desc = [
    `${m.governing_body} ${m.meeting_type}`,
    `Location: ${m.location_name}\\n${m.location}`,
    m.public_comment ? "Public comment period available" : "",
    m.live_stream_url ? `Live Stream: ${m.live_stream_url}` : "",
    m.agenda_url ? `Agenda: ${m.agenda_url}` : "",
    `Source: ${m.source_url}`,
    "Generated by PGH Civic Pulse",
  ].filter(Boolean).join("\\n");

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//PGH Civic Pulse//EN",
    "BEGIN:VEVENT",
    `DTSTART;TZID=${m.timezone}:${dt}`,
    `DTEND;TZID=${m.timezone}:${endDt}`,
    `SUMMARY:${m.governing_body} — ${m.meeting_type}`,
    `LOCATION:${m.location_name}, ${m.location}`,
    `DESCRIPTION:${desc}`,
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\r\n");
}

function downloadIcs(m: UpcomingMeeting) {
  const ics = generateIcs(m);
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${m.governing_body.replace(/\s+/g, "-")}-${m.date}.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Color mapping for governing bodies
function bodyColor(body: string) {
  const l = body.toLowerCase();
  if (l.includes("county") && !l.includes("port authority")) return "bg-blue-600 text-white";
  if (l.includes("city council")) return "bg-[hsl(47,95%,55%)] text-[hsl(215,25%,12%)]";
  if (l.includes("school") || l.includes("pps")) return "bg-green-600 text-white";
  if (l.includes("zoning")) return "bg-orange-600 text-white";
  if (l.includes("planning commission")) return "bg-amber-600 text-white";
  if (l.includes("ura")) return "bg-purple-600 text-white";
  if (l.includes("housing") || l.includes("hacp")) return "bg-teal-600 text-white";
  if (l.includes("regional transit") || l.includes("prt")) return "bg-sky-600 text-white";
  if (l.includes("water") || l.includes("pwsa")) return "bg-cyan-600 text-white";
  return "bg-muted text-muted-foreground";
}

function shortLabel(body: string): string {
  const l = body.toLowerCase();
  if (l.includes("county") && !l.includes("port authority")) return "County";
  if (l.includes("city council")) return "City";
  if (l.includes("school") || l.includes("pps")) return "Schools";
  if (l.includes("zoning")) return "Zoning";
  if (l.includes("planning commission")) return "Planning";
  if (l.includes("ura")) return "URA";
  if (l.includes("housing") || l.includes("hacp")) return "HACP";
  if (l.includes("regional transit") || l.includes("prt")) return "Transit";
  if (l.includes("water") || l.includes("pwsa")) return "PWSA";
  return body.split("(")[0].trim();
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr + "T12:00:00");
  return d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
}

/** Parse time string to {h24, min} - handles "14:00", "2:00 PM", "1:00 PM - 5:00 PM" etc. */
function parseTime(time: string): { h24: number; min: number } {
  if (!time) return { h24: 0, min: 0 };
  const trimmed = time.trim();
  
  // AM/PM format — also catches range formats like "1:00 PM - 5:00 PM" (uses start time)
  const ampmMatch = trimmed.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i);
  if (ampmMatch) {
    let h = parseInt(ampmMatch[1], 10);
    const m = parseInt(ampmMatch[2], 10);
    const period = ampmMatch[3].toUpperCase();
    if (period === "PM" && h !== 12) h += 12;
    if (period === "AM" && h === 12) h = 0;
    return { h24: isNaN(h) ? 0 : h, min: isNaN(m) ? 0 : m };
  }
  // 24h format fallback (e.g. "14:00")
  const colonMatch = trimmed.match(/(\d{1,2}):(\d{2})/);
  if (colonMatch) {
    const h = parseInt(colonMatch[1], 10);
    const m = parseInt(colonMatch[2], 10);
    return { h24: isNaN(h) ? 0 : h, min: isNaN(m) ? 0 : m };
  }
  // Hour-only fallback (e.g. "14" or "2 PM")
  const hourOnly = trimmed.match(/(\d{1,2})\s*(AM|PM)?/i);
  if (hourOnly) {
    let h = parseInt(hourOnly[1], 10);
    if (hourOnly[2]?.toUpperCase() === "PM" && h !== 12) h += 12;
    if (hourOnly[2]?.toUpperCase() === "AM" && h === 12) h = 0;
    return { h24: isNaN(h) ? 0 : h, min: 0 };
  }
  return { h24: 0, min: 0 };
}

function formatTime(time: string): string {
  if (!time) return "TBD";
  const { h24, min } = parseTime(time);
  const period = h24 >= 12 ? "PM" : "AM";
  const h12 = h24 > 12 ? h24 - 12 : h24 === 0 ? 12 : h24;
  return `${h12}:${String(min).padStart(2, "0")} ${period}`;
}

function isThisWeek(dateStr: string): boolean {
  const now = new Date();
  const meetDate = new Date(dateStr + "T12:00:00");
  const diffDays = Math.ceil((meetDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
  return diffDays >= 0 && diffDays <= 7;
}

function isPast(dateStr: string): boolean {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  return new Date(dateStr + "T23:59:59") < now;
}

export default function Calendar() {
  const { data: meetings = [], isLoading } = useQuery<UpcomingMeeting[]>({
    queryKey: ["/api/upcoming-meetings"],
  });

  const [filter, setFilter] = useState<string>("all");

  const bodies = Array.from(new Set(meetings.map((m) => shortLabel(m.governing_body))));

  const filtered = filter === "all"
    ? meetings
    : meetings.filter((m) => shortLabel(m.governing_body) === filter);

  // Sort by date — exclude meetings with invalid/empty dates
  const sorted = [...filtered]
    .filter((m) => m.date && m.date.trim() !== "" && m.date !== "TBD")
    .filter((m) => !isPast(m.date))
    .sort((a, b) => {
      const dateCmp = a.date.localeCompare(b.date);
      if (dateCmp !== 0) return dateCmp;
      return a.time.localeCompare(b.time);
    });

  // Group by week
  const thisWeek = sorted.filter((m) => isThisWeek(m.date));
  const later = sorted.filter((m) => !isThisWeek(m.date));

  if (isLoading) {
    return (
      <div className="p-6 space-y-4">
        <div className="h-8 bg-muted animate-pulse rounded w-48" />
        {[1, 2, 3].map((i) => (
          <div key={i} className="h-24 bg-muted animate-pulse rounded-lg" />
        ))}
      </div>
    );
  }

  return (
    <div className="p-6 space-y-5" data-testid="calendar-page">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold tracking-tight" data-testid="text-page-title">
            Upcoming Meetings
          </h2>
          <p className="text-sm text-muted-foreground mt-0.5">
            Add any meeting to your calendar with one click
          </p>
        </div>
        <Badge variant="outline" className="text-xs">
          {sorted.length} upcoming
        </Badge>
      </div>

      {/* Filters */}
      <div className="flex gap-2 flex-wrap">
        <button
          data-testid="filter-all-cal"
          onClick={() => setFilter("all")}
          className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
            filter === "all"
              ? "bg-primary text-primary-foreground"
              : "bg-muted text-muted-foreground hover:bg-muted/80"
          }`}
        >
          All
        </button>
        {bodies.map((body) => (
          <button
            key={body}
            data-testid={`filter-cal-${body.toLowerCase()}`}
            onClick={() => setFilter(body)}
            className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
              filter === body
                ? "bg-primary text-primary-foreground"
                : "bg-muted text-muted-foreground hover:bg-muted/80"
            }`}
          >
            {body}
          </button>
        ))}
      </div>

      {/* This Week */}
      {thisWeek.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-3">
            This Week
          </h3>
          <div className="grid gap-3">
            {thisWeek.map((m, i) => (
              <MeetingEventCard key={`tw-${i}`} meeting={m} highlight />
            ))}
          </div>
        </div>
      )}

      {/* Coming Up */}
      {later.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-3">
            Coming Up
          </h3>
          <div className="grid gap-3">
            {later.map((m, i) => (
              <MeetingEventCard key={`later-${i}`} meeting={m} />
            ))}
          </div>
        </div>
      )}

      {sorted.length === 0 && (
        <div className="text-center py-12 text-muted-foreground">
          <CalendarPlus className="h-8 w-8 mx-auto mb-2 opacity-50" />
          <p className="text-sm">No upcoming meetings found</p>
        </div>
      )}
    </div>
  );
}

function MeetingEventCard({ meeting: m, highlight = false }: { meeting: UpcomingMeeting; highlight?: boolean }) {
  return (
    <Card
      data-testid={`upcoming-${m.date}-${shortLabel(m.governing_body).toLowerCase()}`}
      className={highlight ? "border-l-4 border-l-[hsl(47,95%,55%)]" : ""}
    >
      <CardContent className="p-4">
        <div className="flex items-start justify-between gap-3">
          {/* Left: Date column */}
          <div className="text-center shrink-0 w-16">
            <div className="text-2xl font-bold tabular-nums leading-none">
              {new Date(m.date + "T12:00:00").getDate()}
            </div>
            <div className="text-[10px] text-muted-foreground uppercase mt-0.5">
              {new Date(m.date + "T12:00:00").toLocaleDateString("en-US", { weekday: "short", month: "short" })}
            </div>
          </div>

          {/* Center: Details */}
          <div className="flex-1 min-w-0 space-y-1.5">
            <div className="flex items-center gap-2 flex-wrap">
              <Badge className={`text-[10px] px-1.5 py-0 ${bodyColor(m.governing_body)}`}>
                {shortLabel(m.governing_body)}
              </Badge>
              <Badge variant="outline" className="text-[10px] px-1.5 py-0">
                {m.meeting_type}
              </Badge>
              {m.public_comment && (
                <Badge variant="outline" className="text-[10px] px-1.5 py-0 border-green-500/50 text-green-600 dark:text-green-400 gap-0.5">
                  <MessageSquare className="h-2.5 w-2.5" />
                  Public Comment
                </Badge>
              )}
            </div>

            <h3 className="text-sm font-medium leading-snug">
              {m.governing_body} — {m.meeting_type}
            </h3>

            <div className="flex items-center gap-4 text-xs text-muted-foreground flex-wrap">
              <span className="flex items-center gap-1">
                <Clock className="h-3 w-3" />
                {formatTime(m.time)} ET
              </span>
              <span className="flex items-center gap-1">
                <MapPin className="h-3 w-3" />
                {m.location_name}
              </span>
            </div>

            <div className="text-[11px] text-muted-foreground/80">
              {m.location}
            </div>

            {/* Links row */}
            <div className="flex items-center gap-3 pt-1">
              {m.live_stream_url && (
                <a
                  href={m.live_stream_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1 text-xs text-red-500 hover:text-red-400 transition-colors"
                >
                  <Video className="h-3 w-3" />
                  Live Stream
                </a>
              )}
              {m.agenda_url && (
                <a
                  href={m.agenda_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  <ExternalLink className="h-3 w-3" />
                  Agenda
                </a>
              )}
            </div>
          </div>

          {/* Right: Calendar actions */}
          <div className="flex flex-col gap-1.5 shrink-0">
            <a
              href={googleCalUrl(m)}
              target="_blank"
              rel="noopener noreferrer"
              data-testid={`gcal-${m.date}-${shortLabel(m.governing_body).toLowerCase()}`}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 transition-colors"
            >
              <CalendarPlus className="h-3.5 w-3.5" />
              Google Cal
            </a>
            <button
              onClick={() => downloadIcs(m)}
              data-testid={`ics-${m.date}-${shortLabel(m.governing_body).toLowerCase()}`}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-muted text-muted-foreground text-xs font-medium hover:bg-muted/80 transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              .ics File
            </button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
